"""scaffold_config: emit a VALID starter dfxm-geo config as TOML text.

The contract is ``validate_config(scaffold_config(...)).ok is True``. Templates are
per-structure; key/block names are sourced from the canonical dfxm-geo configs
(``data/configs/default.toml``, ``data/configs/al_oblique_figure3.toml``) and
``docs/crystal-structures.md``:

- FCC symmetric runs need no [crystal]/[geometry] mount (the simplified path).
- Non-FCC runs need an explicit mount + ``structure_type`` + a Poisson source
  (``material`` resolves ν from the built-in table — the non-FCC Poisson gate
  raises without it).
- A single-reflection oblique run (BCC/HCP) requires an EXACT ``eta`` in the
  [geometry] block; the validator cross-checks it against ``compute_omega_eta``
  and rejects a wrong value (e.g. ``eta = 0.0``). We compute it here.
"""

from __future__ import annotations

import math
import tomllib

from dfxm_geo.crystal.oblique import compute_omega_eta
from dfxm_geo.reciprocal_space.kernel import _crystal_mount_from_toml

# Cubic lattice parameters (metres) for the supported non-FCC materials. Sourced
# from standard crystallographic tables; |b| for BCC is derived from the cell
# matrix, so the value matters physically (FCC uses a hard-coded |b| constant).
_LATTICE_A_M: dict[str, float] = {
    "W": 3.165e-10,   # tungsten, BCC
    "Fe": 2.87e-10,   # alpha-iron, BCC
}

# Mount used for non-FCC cubic oblique runs. Matches the BCC example in
# docs/crystal-structures.md ("Oblique-eta requirement (BCC and HCP)").
_BCC_MOUNT = {
    "mount_x": (1, 1, 0),
    "mount_y": (-1, 1, 0),
    "mount_z": (0, 0, 1),
}


def _vec(v: tuple[int, int, int]) -> str:
    return f"[{v[0]}, {v[1]}, {v[2]}]"


def _crystal_block_lines(crystal: dict[str, object]) -> list[str]:
    """Serialise a crystal dict to TOML lines (without the ``[crystal]`` header).

    Used both by ``scaffold_config`` (to build the emitted text) and by
    ``_compute_eta`` (to build the round-trip TOML for the validator).  The two
    callers MUST produce byte-identical output so the eta the scaffold emits
    matches what the validator recomputes from the same text.
    """
    result: list[str] = []
    for key, val in crystal.items():
        if isinstance(val, list):
            result.append(f"{key} = {_vec(tuple(val))}")  # type: ignore[arg-type]
        elif isinstance(val, str):
            result.append(f'{key} = "{val}"')
        else:
            result.append(f"{key} = {val}")
    return result


def scaffold_config(
    *,
    material: str | None = None,
    structure_type: str | None = None,
    reflection: tuple[int, int, int] | None = None,
    energy_keV: float = 17.0,
    geometry_mode: str = "symmetric",
    cif_path: str | None = None,
    scan_mode: str = "single",
    backend: str = "analytic",
) -> str:
    """Emit a valid starter dfxm-geo config as TOML text.

    See module docstring for the per-structure contract. The returned text is
    guaranteed to satisfy ``validate_config(...).ok`` for the supported cases
    (default FCC symmetric, explicit FCC aluminium, BCC cubic oblique).

    Current limitations
    -------------------
    * **FCC** scaffolding assumes aluminium. Passing ``material`` with any value
      other than ``"Al"`` (or ``None``) raises ``NotImplementedError`` because
      the scaffold hard-codes Al's Poisson ratio and emits no ``[crystal]`` block.
      Pass ``material=None`` or ``material="Al"`` for the FCC path.
    * **Non-FCC lattice lookup** only covers the materials listed in
      ``_LATTICE_A_M`` (currently W and Fe). Any other non-FCC material raises
      ``ValueError`` — there is no silent fallback to a wrong lattice constant.
    * ``scan_mode`` is accepted but currently a no-op; no scan block is emitted.
    """
    hkl = reflection or (-1, 1, -1)
    is_fcc = structure_type is None or structure_type.lower() == "fcc"
    is_oblique = geometry_mode == "oblique"

    # Guard: FCC scaffolding is Al-only. Be loud rather than silently wrong.
    if is_fcc and material is not None and material != "Al":
        raise NotImplementedError(
            f"FCC scaffolding currently assumes aluminium (Al). "
            f"Material '{material}' is not supported on the FCC path. "
            f"Pass material=None or material='Al', or choose a non-FCC structure_type."
        )

    lines: list[str] = [
        "# Generated by dfxm-geo-mcp scaffold_config.",
        "",
        "[reciprocal]",
        f"hkl = {_vec(hkl)}",
        f"keV = {energy_keV}",
        f'backend = "{backend}"',
        # The analytic backend renders without a beamstop; only the MC backend needs one.
        f"beamstop = {'true' if backend == 'mc' else 'false'}",
    ]

    # FCC symmetric: simplified path needs no [crystal] mount / [geometry] block.
    if is_fcc and not is_oblique and cif_path is None:
        return "\n".join(lines) + "\n"

    # Guard: non-FCC material must be in the lattice table.
    if not is_fcc and cif_path is None:
        mat = material or ""
        if mat not in _LATTICE_A_M:
            raise ValueError(
                f"No lattice constant for material '{mat}'. "
                f"Supported non-FCC materials: {list(_LATTICE_A_M)}. "
                f"Add the material to _LATTICE_A_M or supply a cif_path."
            )

    # Build the [crystal] block as a dict first so we can construct the exact
    # CrystalMount the validator will see and compute eta against it.
    crystal: dict[str, object] = {}
    if cif_path is not None:
        crystal["cif"] = cif_path
    else:
        crystal["lattice"] = "cubic"
        crystal["a"] = _LATTICE_A_M[material or ""]
        if not is_fcc:
            crystal["structure_type"] = structure_type
        if material is not None:
            crystal["material"] = material  # resolves Poisson ratio from the table
        crystal["mount_x"] = list(_BCC_MOUNT["mount_x"])
        crystal["mount_y"] = list(_BCC_MOUNT["mount_y"])
        crystal["mount_z"] = list(_BCC_MOUNT["mount_z"])

    crystal_lines = ["", "[crystal]"] + _crystal_block_lines(crystal)

    geometry_lines: list[str] = []
    if is_oblique:
        eta = _compute_eta(crystal, hkl, energy_keV)
        geometry_lines = ["", "[geometry]", 'mode = "oblique"', f"eta = {eta:.12f}"]

    return "\n".join(lines + crystal_lines + geometry_lines) + "\n"


def _compute_eta(
    crystal: dict[str, object], hkl: tuple[int, int, int], energy_keV: float
) -> float:
    """Compute the exact oblique eta (radians) the [geometry] validator requires.

    Builds the same CrystalMount the validator will from the emitted [crystal]
    block, then takes the first non-NaN of (eta_1, eta_2) from compute_omega_eta.
    """
    # Round-trip through tomllib so the mount is built from the literal text we emit.
    crystal_toml = "[crystal]\n" + "\n".join(_crystal_block_lines(crystal))
    data = tomllib.loads(crystal_toml)
    mount = _crystal_mount_from_toml(data["crystal"])
    geom = compute_omega_eta(mount, hkl=hkl, keV=energy_keV)
    eta = geom.eta_1 if not math.isnan(geom.eta_1) else geom.eta_2
    if math.isnan(eta):
        raise ValueError(
            f"Reflection {hkl} is not Laue-reachable at {energy_keV} keV for the "
            f"scaffolded mount; cannot emit a valid oblique eta."
        )
    return float(eta)
