"""scaffold_config: emit a VALID starter dfxm-geo config as TOML text.

The contract is ``validate_config(scaffold_config(...)).ok is True``. Templates are
per-structure; key/block names are sourced from the canonical dfxm-geo configs
(``data/configs/default.toml``, ``data/configs/al_oblique_figure3.toml``) and
``docs/crystal-structures.md``:

- FCC symmetric runs need no [crystal]/[geometry] mount (the simplified path).
- Non-FCC runs need an explicit mount + ``structure_type`` + a Poisson source
  (``material`` resolves ν from the built-in table — the non-FCC Poisson gate
  raises without it).
- A single-reflection oblique run (BCC/HCP) requires an EXACT ``eta`` in the
  [geometry] block; the validator cross-checks it against ``compute_omega_eta``
  and rejects a wrong value (e.g. ``eta = 0.0``). We compute it here.
"""

from __future__ import annotations

import math
import tomllib

from dfxm_geo.crystal.oblique import compute_omega_eta
from dfxm_geo.reciprocal_space.kernel import _crystal_mount_from_toml

# Cubic lattice parameters (metres) for the supported non-FCC materials. Sourced
# from standard crystallographic tables; |b| for BCC is derived from the cell
# matrix, so the value matters physically (FCC uses a hard-coded |b| constant).
_LATTICE_A_M: dict[str, float] = {
    "W": 3.165e-10,   # tungsten, BCC
    "Fe": 2.87e-10,   # alpha-iron, BCC
}
_DEFAULT_CUBIC_A_M = 3.165e-10

# Mount used for non-FCC cubic oblique runs. Matches the BCC example in
# docs/crystal-structures.md ("Oblique-eta requirement (BCC and HCP)").
_BCC_MOUNT = {
    "mount_x": (1, 1, 0),
    "mount_y": (-1, 1, 0),
    "mount_z": (0, 0, 1),
}


def _vec(v: tuple[int, int, int]) -> str:
    return f"[{v[0]}, {v[1]}, {v[2]}]"


def scaffold_config(
    *,
    material: str | None = None,
    structure_type: str | None = None,
    reflection: tuple[int, int, int] | None = None,
    energy_keV: float = 17.0,
    geometry_mode: str = "symmetric",
    cif_path: str | None = None,
    scan_mode: str = "single",
    backend: str = "analytic",
) -> str:
    """Emit a valid starter dfxm-geo config as TOML text.

    See module docstring for the per-structure contract. The returned text is
    guaranteed to satisfy ``validate_config(...).ok`` for the supported cases
    (default FCC symmetric, explicit FCC, BCC cubic oblique).
    """
    hkl = reflection or (-1, 1, -1)
    is_fcc = structure_type is None or structure_type.lower() == "fcc"
    is_oblique = geometry_mode == "oblique"

    lines: list[str] = [
        "# Generated by dfxm-geo-mcp scaffold_config.",
        "",
        "[reciprocal]",
        f"hkl = {_vec(hkl)}",
        f"keV = {energy_keV}",
        f'backend = "{backend}"',
        # The analytic backend renders without a beamstop; only the MC backend needs one.
        f"beamstop = {'true' if backend == 'mc' else 'false'}",
    ]

    # FCC symmetric: simplified path needs no [crystal] mount / [geometry] block.
    if is_fcc and not is_oblique and cif_path is None:
        return "\n".join(lines) + "\n"

    # Build the [crystal] block as a dict first so we can construct the exact
    # CrystalMount the validator will see and compute eta against it.
    crystal: dict[str, object] = {}
    if cif_path is not None:
        crystal["cif"] = cif_path
    else:
        crystal["lattice"] = "cubic"
        crystal["a"] = _LATTICE_A_M.get(material or "", _DEFAULT_CUBIC_A_M)
        if not is_fcc:
            crystal["structure_type"] = structure_type
        if material is not None:
            crystal["material"] = material  # resolves Poisson ratio from the table
        crystal["mount_x"] = list(_BCC_MOUNT["mount_x"])
        crystal["mount_y"] = list(_BCC_MOUNT["mount_y"])
        crystal["mount_z"] = list(_BCC_MOUNT["mount_z"])

    crystal_lines = ["", "[crystal]"]
    for key, val in crystal.items():
        if isinstance(val, list):
            crystal_lines.append(f"{key} = {_vec(tuple(val))}")  # type: ignore[arg-type]
        elif isinstance(val, str):
            crystal_lines.append(f'{key} = "{val}"')
        else:
            crystal_lines.append(f"{key} = {val}")

    geometry_lines: list[str] = []
    if is_oblique:
        eta = _compute_eta(crystal, hkl, energy_keV)
        geometry_lines = ["", "[geometry]", 'mode = "oblique"', f"eta = {eta:.12f}"]

    return "\n".join(lines + crystal_lines + geometry_lines) + "\n"


def _compute_eta(
    crystal: dict[str, object], hkl: tuple[int, int, int], energy_keV: float
) -> float:
    """Compute the exact oblique eta (radians) the [geometry] validator requires.

    Builds the same CrystalMount the validator will from the emitted [crystal]
    block, then takes the first non-NaN of (eta_1, eta_2) from compute_omega_eta.
    """
    # Round-trip through tomllib so the mount is built from the literal text we emit.
    crystal_toml = "[crystal]\n" + "\n".join(
        f"{k} = {_vec(tuple(v))}"  # type: ignore[arg-type]
        if isinstance(v, list)
        else (f'{k} = "{v}"' if isinstance(v, str) else f"{k} = {v}")
        for k, v in crystal.items()
    )
    data = tomllib.loads(crystal_toml)
    mount = _crystal_mount_from_toml(data["crystal"])
    geom = compute_omega_eta(mount, hkl=hkl, keV=energy_keV)
    eta = geom.eta_1 if not math.isnan(geom.eta_1) else geom.eta_2
    if math.isnan(eta):
        raise ValueError(
            f"Reflection {hkl} is not Laue-reachable at {energy_keV} keV for the "
            f"scaffolded mount; cannot emit a valid oblique eta."
        )
    return float(eta)
